### ISSUE TITLE
Building irods-webdav 1 required artifact is missing: org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT

### ISSUE THREAD

**Issue by salsa-dev** [DICE-UNC/irods-webdav#10]
Hi, I get an error when following instructions https://irods.org/post/how-to-drag-and-drop-access-to-irods-with-webdav/

The log is here:

```
opergrid@bim:~/irods-webdav$ mvn package -e -DskipTests
+ Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building irods-webav
[INFO]    task-segment: [package]
[INFO] ------------------------------------------------------------------------
[INFO] snapshot org.irods.jargon:jargon-core:4.0.2.3-SNAPSHOT: checking for updates from dice.repository snaps
Downloading: http://mirrors.ibiblio.org/pub/mirrors/maven2/org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.pom
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:pom:4.0.2.3-SNAPSHOT' in repository ibiblio.repository (http://mirrors.ibiblio.org/pub/mirrors/maven2)
Downloading: http://milton.io/maven//org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.pom
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:pom:4.0.2.3-SNAPSHOT' in repository ettrema-repo (http://milton.io/maven/)
Downloading: https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots/org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.pom
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:pom:4.0.2.3-SNAPSHOT' in repository dice.repository snaps (https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots)
Downloading: http://download.java.net/maven/2/org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.pom
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:pom:4.0.2.3-SNAPSHOT' in repository java.net2 (http://download.java.net/maven/2)
Downloading: http://mirrors.ibiblio.org/pub/mirrors/maven2/org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.jar
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT' in repository ibiblio.repository (http://mirrors.ibiblio.org/pub/mirrors/maven2)
Downloading: http://milton.io/maven//org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.jar
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT' in repository ettrema-repo (http://milton.io/maven/)
Downloading: https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots/org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.jar
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT' in repository dice.repository snaps (https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots)
Downloading: http://download.java.net/maven/2/org/irods/jargon/jargon-core/4.0.2.3-SNAPSHOT/jargon-core-4.0.2.3-SNAPSHOT.jar
[INFO] Unable to find resource 'org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT' in repository java.net2 (http://download.java.net/maven/2)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Missing:
----------
1) org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.irods.jargon -DartifactId=jargon-core -Dversion=4.0.2.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.irods.jargon -DartifactId=jargon-core -Dversion=4.0.2.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) org.irods.jargon:irods-webdav:war:0.0.1-SNAPSHOT
        2) org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT

----------
1 required artifact is missing.

for artifact: 
  org.irods.jargon:irods-webdav:war:0.0.1-SNAPSHOT

from the specified remote repositories:
  dice.repository snaps (https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots),
  central (http://repo1.maven.org/maven2),
  dice.repository (https://raw.github.com/DICE-UNC/DICE-Maven/master/releases),
  java.net2 (http://download.java.net/maven/2),
  ettrema-repo (http://milton.io/maven/),
  ibiblio.repository (http://mirrors.ibiblio.org/pub/mirrors/maven2)



[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Missing:
----------
1) org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.irods.jargon -DartifactId=jargon-core -Dversion=4.0.2.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.irods.jargon -DartifactId=jargon-core -Dversion=4.0.2.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) org.irods.jargon:irods-webdav:war:0.0.1-SNAPSHOT
        2) org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT

----------
1 required artifact is missing.

for artifact: 
  org.irods.jargon:irods-webdav:war:0.0.1-SNAPSHOT

from the specified remote repositories:
  dice.repository snaps (https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots),
  central (http://repo1.maven.org/maven2),
  dice.repository (https://raw.github.com/DICE-UNC/DICE-Maven/master/releases),
  java.net2 (http://download.java.net/maven/2),
  ettrema-repo (http://milton.io/maven/),
  ibiblio.repository (http://mirrors.ibiblio.org/pub/mirrors/maven2)


        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:711)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
        at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.artifact.resolver.MultipleArtifactsNotFoundException: Missing:
----------
1) org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.irods.jargon -DartifactId=jargon-core -Dversion=4.0.2.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.irods.jargon -DartifactId=jargon-core -Dversion=4.0.2.3-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
        1) org.irods.jargon:irods-webdav:war:0.0.1-SNAPSHOT
        2) org.irods.jargon:jargon-core:jar:4.0.2.3-SNAPSHOT

----------
1 required artifact is missing.

for artifact: 
  org.irods.jargon:irods-webdav:war:0.0.1-SNAPSHOT

from the specified remote repositories:
  dice.repository snaps (https://raw.github.com/DICE-UNC/DICE-Maven/master/snapshots),
  central (http://repo1.maven.org/maven2),
  dice.repository (https://raw.github.com/DICE-UNC/DICE-Maven/master/releases),
  java.net2 (http://download.java.net/maven/2),
  ettrema-repo (http://milton.io/maven/),
  ibiblio.repository (http://mirrors.ibiblio.org/pub/mirrors/maven2)


        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:360)
        at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolveTransitively(DefaultArtifactResolver.java:304)
        at org.apache.maven.plugin.DefaultPluginManager.resolveTransitiveDependencies(DefaultPluginManager.java:1499)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:442)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
        ... 17 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13 seconds
[INFO] Finished at: Thu May 21 17:38:04 MSK 2015
[INFO] Final Memory: 16M/93M
[INFO] ------------------------------------------------------------------------
```

**Comment by michael-conway** [comment]
Hey just pushed.  I need to get that up to maven.  Sorry. Can have in 30 or
change pom back to 4.0.3.1 if need be.

**Comment by michael-conway** [comment]
Doing a bunch of things getting ready for release...sorry

**Comment by michael-conway** [comment]
That version of jargon is now pushed to the github DICE-Maven repo
We are planning on releasing WebDav along with the upcoming Jargon 4.0.2.3-RELEASE, hence the update.

This will be compatible and tested with iRODS 4.1 as well as 3.3.1-4.0.3

iPlant is also testing this and we'll be adding some fixes and polish to it before the release, doing a few performance optimizations.
