### ISSUE TITLE
locking errors using enterprise keys

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-webdav#23]
webdav deployed with enterprise keys and locking gives error:

``
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.BasicAuthFilter  - doFilter()
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.WebDavAuthUtils  - getIRODSAccountFromBasicAuthValues
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.WebDavAuthUtils  - index of end of basic prefix:5
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.WebDavAuthUtils  - index of end of basic prefix:5
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.WebDavAuthUtils  - credentials:test1
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.WebDavAuthUtils  - webDavConfig:WebDavConfig [host=dfc-test-irods1.edc.renci.org, zone=dfc1, port=1247, defaultStorageResource=, authScheme=STANDARD, realm=irods, cacheFileDemographics=true, defaultStartingLocationEnum=USER_HOME, providedDefaultStartingLocation=, usePackingStreams=true]
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.BasicAuthFilter  - account for auth:test1
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.IrodsAuthService  - authenticate()
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.IrodsAuthService  - look in cache for cached login
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.IrodsAuthService  - in thread local cache
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.BasicAuthFilter  - authResponse:org.irods.jargon.core.connection.auth.AuthResponse@51da095d
65872341 [http-bio-8080-exec-3] DEBUG org.irods.jargon.webdav.authfilter.BasicAuthFilter  - success!
65872341 [http-bio-8080-exec-3] INFO  io.milton.http.HttpManager  - LOCK :: dfc-test-tomcat2.edc.renci.org///zoom/milton.txt start
65872341 [http-bio-8080-exec-3] WARN  io.milton.http.StandardFilter  - No method handler for: LOCK Please check that dav level 2 protocol support is enabled
65872341 [http-bio-8080-exec-3] INFO  io.milton.http.HttpManager  - LOCK :: dfc-test-tomcat2.edc.renci.org///zoom/milton.txt finished 0ms, Status:HTTP/1.1 501, Length:null

```

**Comment by michael-conway** [comment]
now getting


``

 15:56:20 EST 2015, specColType=NORMAL, collectionPath=, cacheDir=, cacheDirty=false, replNumber=0, standInGeneratedObjStat=false]
805347 [http-bio-8080-exec-8] INFO  org.irods.jargon.webdav.resource.IrodsFileSystemResourceFactory  - file is a data object
805347 [http-bio-8080-exec-8] INFO  org.irods.jargon.webdav.resource.IrodsFileSystemResourceFactory  - resolved as resource:org.irods.jargon.webdav.resource.IrodsFileResource@778c8b2e
805347 [http-bio-8080-exec-8] INFO  org.irods.jargon.webdav.resource.IrodsSecurityManager  - authenticate()
805347 [http-bio-8080-exec-8] DEBUG org.irods.jargon.webdav.authfilter.IrodsAuthService  - authenticate()
805347 [http-bio-8080-exec-8] DEBUG org.irods.jargon.webdav.authfilter.IrodsAuthService  - look in cache for cached login
805347 [http-bio-8080-exec-8] DEBUG org.irods.jargon.webdav.authfilter.IrodsAuthService  - in thread local cache
805347 [http-bio-8080-exec-8] INFO  org.irods.jargon.webdav.resource.IrodsSecurityManager  - storing authResponse in threadlocal as authResponseCache
805348 [http-bio-8080-exec-8] INFO  org.irods.jargon.webdav.resource.IrodsFileResource  - getCurrentLock()
805348 [http-bio-8080-exec-8] WARN  org.irods.jargon.webdav.resource.IrodsFileResource  - getCurrentLock called, but no lock manager: file: /dfc1/home/test1/zoom/milton.txt
805348 [http-bio-8080-exec-8] INFO  org.irods.jargon.webdav.resource.IrodsFileResource  - lock()
805348 [http-bio-8080-exec-8] ERROR io.milton.http.StandardFilter  - exception sending content
java.lang.NullPointerException
	at org.irods.jargon.webdav.resource.IrodsFileResource.lock(IrodsFileResource.java:303)
	at io.milton.http.webdav2.LockHandler.processNewLock(LockHandler.java:211)
	at io.milton.http.webdav2.LockHandler.processExistingResource(LockHandler.java:93)
	at io.milton.http.webdav2.LockHandler.process(LockHandler.java:69)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at io.milton.servlet.SpringMiltonFilter.doMiltonProcessing(SpringMiltonFilter.java:260)
	at io.milton.servlet.SpringMiltonFilter.doFilter(SpringMiltonFilter.java:236)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.irods.jargon.webdav.authfilter.BasicAuthFilter.doFilter(BasicAuthFilter.java:90)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```
