### ISSUE TITLE
error renaming folder using Mac Finder

### ISSUE THREAD

**Issue by michael-conway** [DICE-UNC/irods-webdav#24]
```
Nov 24 13:57:11 pid:23626 ERROR: _rsDataObjRename: dest coll /dfc1/home/test1/untitled folder/hhhh does not exist, status = -808000

```

when creating a new folder in finder, then trying to rename it. Note that folder itself is created

**Comment by michael-conway** [comment]
extended look moving zoom to zoom2 (as a dir)

```
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl  - ObjStat [absolutePath=/dfc1/home/test1/zoom, objectPath=, objectType=COLLECTION, dataId=17471, checksum=, ownerName=test1, ownerZone=dfc1, objSize=0, createdAt=Wed Sep 16 09:24:04 EDT 2015, modifiedAt=Fri Nov 20 12:55:34 EST 2015, specColType=NORMAL, collectionPath=, cacheDir=, cacheDirty=false, replNumber=0, standInGeneratedObjStat=false]
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.DataTransferOperationsImpl  - see if this is just a physical move
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.DataTransferOperationsImpl  - treat as a normal move
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.DataTransferOperationsImpl  - moveOperation()
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.DataTransferOperationsImpl  - target file:/dfc1/home/test1/zoom2
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.io.IRODSFileImpl  - isDirectory() for path:/dfc1/home/test1/zoom2
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - getObjStat(final String irodsAbsolutePath)
1118733 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl  - retrieveObjectStatForPathWithHeuristicPathGuessing()
1118736 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl  - got a file not found, try to heuristically produce an objstat
1118736 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionIteratorAOImpl  - handleNoObjStatUnderRootOrHomeByLookingForPublicAndHome()
1118736 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionIteratorAOImpl  - really is a not found for file:/dfc1/home/test1/zoom2
1118737 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.io.IRODSFileImpl  - file not found
1118737 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.DataTransferOperationsImpl  - target file isDir? false
1118737 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.io.IRODSFileImpl  - isFile() for path:/dfc1/home/test1/zoom
1118737 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - getObjStat(final String irodsAbsolutePath)
1118737 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl  - retrieveObjectStatForPathWithHeuristicPathGuessing()
1118740 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl  - ObjStat [absolutePath=/dfc1/home/test1/zoom, objectPath=, objectType=COLLECTION, dataId=17471, checksum=, ownerName=test1, ownerZone=dfc1, objSize=0, createdAt=Wed Sep 16 09:24:04 EDT 2015, modifiedAt=Fri Nov 20 12:55:34 EST 2015, specColType=NORMAL, collectionPath=, cacheDir=, cacheDirty=false, replNumber=0, standInGeneratedObjStat=false]
1118740 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.io.IRODSFileImpl  - isFile() for path:/dfc1/home/test1/zoom
1118740 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.IRODSFileSystemAOImpl  - getObjStat(final String irodsAbsolutePath)
1118740 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl  - retrieveObjectStatForPathWithHeuristicPathGuessing()
1118743 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.CollectionAndDataObjectListAndSearchAOImpl  - ObjStat [absolutePath=/dfc1/home/test1/zoom, objectPath=, objectType=COLLECTION, dataId=17471, checksum=, ownerName=test1, ownerZone=dfc1, objSize=0, createdAt=Wed Sep 16 09:24:04 EDT 2015, modifiedAt=Fri Nov 20 12:55:34 EST 2015, specColType=NORMAL, collectionPath=, cacheDir=, cacheDirty=false, replNumber=0, standInGeneratedObjStat=false]
1118743 [http-bio-8080-exec-2] INFO  org.irods.jargon.core.pub.DataTransferOperationsImpl  - move is for a collection
1118747 [http-bio-8080-exec-2] ERROR org.irods.jargon.core.pub.DataTransferOperationsImpl  - jargon exception in move operation
org.irods.jargon.core.exception.DataNotFoundException: No data found
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:150)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:235)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.moveOperation(DataTransferOperationsImpl.java:154)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.move(DataTransferOperationsImpl.java:244)
	at org.irods.jargon.webdav.resource.IrodsDirectoryResource.moveTo(IrodsDirectoryResource.java:534)
	at io.milton.http.webdav.MoveHandler.processExistingResource(MoveHandler.java:147)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:122)
	at io.milton.http.webdav.MoveHandler.processResource(MoveHandler.java:87)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.webdav.MoveHandler.process(MoveHandler.java:92)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at io.milton.servlet.SpringMiltonFilter.doMiltonProcessing(SpringMiltonFilter.java:260)
	at io.milton.servlet.SpringMiltonFilter.doFilter(SpringMiltonFilter.java:236)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.irods.jargon.webdav.authfilter.BasicAuthFilter.doFilter(BasicAuthFilter.java:90)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
1118748 [http-bio-8080-exec-2] ERROR org.irods.jargon.webdav.resource.IrodsDirectoryResource  - error in move operation
org.irods.jargon.core.exception.DataNotFoundException: No data found
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:150)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:235)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.moveOperation(DataTransferOperationsImpl.java:154)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.move(DataTransferOperationsImpl.java:244)
	at org.irods.jargon.webdav.resource.IrodsDirectoryResource.moveTo(IrodsDirectoryResource.java:534)
	at io.milton.http.webdav.MoveHandler.processExistingResource(MoveHandler.java:147)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:122)
	at io.milton.http.webdav.MoveHandler.processResource(MoveHandler.java:87)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.webdav.MoveHandler.process(MoveHandler.java:92)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at io.milton.servlet.SpringMiltonFilter.doMiltonProcessing(SpringMiltonFilter.java:260)
	at io.milton.servlet.SpringMiltonFilter.doFilter(SpringMiltonFilter.java:236)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.irods.jargon.webdav.authfilter.BasicAuthFilter.doFilter(BasicAuthFilter.java:90)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
1118748 [http-bio-8080-exec-2] ERROR io.milton.http.StandardFilter  - exception sending content
org.irods.jargon.webdav.exception.WebDavRuntimeException: unable to move directory
	at org.irods.jargon.webdav.resource.IrodsDirectoryResource.moveTo(IrodsDirectoryResource.java:540)
	at io.milton.http.webdav.MoveHandler.processExistingResource(MoveHandler.java:147)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:187)
	at io.milton.http.ResourceHandlerHelper.processResource(ResourceHandlerHelper.java:122)
	at io.milton.http.webdav.MoveHandler.processResource(MoveHandler.java:87)
	at io.milton.http.ResourceHandlerHelper.process(ResourceHandlerHelper.java:118)
	at io.milton.http.webdav.MoveHandler.process(MoveHandler.java:92)
	at io.milton.http.StandardFilter.process(StandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:40)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at io.milton.servlet.SpringMiltonFilter.doMiltonProcessing(SpringMiltonFilter.java:260)
	at io.milton.servlet.SpringMiltonFilter.doFilter(SpringMiltonFilter.java:236)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.irods.jargon.webdav.authfilter.BasicAuthFilter.doFilter(BasicAuthFilter.java:90)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:931)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.irods.jargon.core.exception.DataNotFoundException: No data found
	at org.irods.jargon.core.connection.IRODSErrorScanner.checkSpecificCodesAndThrowIfExceptionLocated(IRODSErrorScanner.java:150)
	at org.irods.jargon.core.connection.IRODSErrorScanner.inspectAndThrowIfNeeded(IRODSErrorScanner.java:123)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.processMessageInfoLessThanZero(AbstractIRODSMidLevelProtocol.java:1172)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:663)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.readMessage(AbstractIRODSMidLevelProtocol.java:629)
	at org.irods.jargon.core.connection.IRODSMidLevelProtocol.irodsFunction(IRODSMidLevelProtocol.java:235)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:174)
	at org.irods.jargon.core.connection.AbstractIRODSMidLevelProtocol.irodsFunction(AbstractIRODSMidLevelProtocol.java:571)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.moveOperation(DataTransferOperationsImpl.java:154)
	at org.irods.jargon.core.pub.DataTransferOperationsImpl.move(DataTransferOperationsImpl.java:244)
	at org.irods.jargon.webdav.resource.IrodsDirectoryResource.moveTo(IrodsDirectoryResource.java:534)
	... 36 more
1118752 [http-bio-8080-exec-2] WARN  io.milton.servlet.ServletResponse  - sendError: HTTP/1.1 500
1118752 [http-bio-8080-exec-2] INFO  io.milton.servlet.ServletResponse  - Closed outputstream after sendError
1118752 [http-bio-8080-exec-2] INFO  io.milton.http.HttpManager  - MOVE :: dfc-test-tomcat2.edc.renci.org///zoom/ finished 52ms, Status:null, Length:null



```
